#!/usr/bin/env ruby
# frozen_string_literal: true

require 'optparse'

options = {}

OptionParser.new do |parser|
  parser.banner = 'Usage: forward-proxy [options]'

  parser.on('-pPORT', '--port=PORT', String, 'Bind to specified port. Default: 9292') do |bind_port|
    options[:bind_port] = bind_port
  end

  parser.on('-bBINDING', '--binding=BINDING', String, 'Bind to the specified ip. Default: 127.0.0.1') do |bind_address|
    options[:bind_address] = bind_address
  end

  parser.on('-tTIMEOUT', '--timeout=TIMEOUT', Integer,
            'Specify the connection timeout in seconds. Default: 300') do |threads|
    options[:timeout] = threads
  end

  parser.on('-cTHREADS', '--threads=THREADS', Integer,
            'Specify the number of client threads. Default: 128') do |threads|
    options[:threads] = threads
  end

  parser.on("-uUSERNAME", "--username=USERNAME", String, "Authenticate user") do |user|
    options[:username] = user
  end

  parser.on("-pPASSWORD", "--password=PASSWORD", String, "Authenticate password") do |pwd|
    options[:password] = pwd
  end

  parser.on('-h', '--help', 'Prints this help.') do
    puts parser
    exit
  end
end.parse!

options[:bind_port] ||= ENV['PORT'] || 9292
options[:username] ||= ENV['USERNAME']
options[:password] ||= ENV['PASSWORD']

require_relative '../lib/forward_proxy'
server = ForwardProxy::Server.new(**options)
server.start
